apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: k8sjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.27
        name: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
          - name: log-volume
            mountPath: /var/log/nginx
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html
        - name: log-volume
          hostPath:
            path: /mnt/data/nginx-logs
            type: DirectoryOrCreate
status: {}
