apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-06T16:24:18Z"
  labels:
    app: my-app
  name: my-app
  namespace: k8sjob
  resourceVersion: "8707"
  uid: fc346a7e-6536-4fb1-a4a1-22aa5126bbbe
spec:
  clusterIP: 10.96.193.38
  clusterIPs:
  - 10.96.193.38
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
